# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: execapi/v1/execapi.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'execapi/v1/execapi.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x65xecapi/v1/execapi.proto\x12\x12tangent.execapi.v1\"3\n\x0b\x45xecRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x13\n\x0bworking_dir\x18\x02 \x01(\t\"B\n\x0c\x45xecResponse\x12\x0e\n\x06stdout\x18\x01 \x01(\t\x12\x0e\n\x06stderr\x18\x02 \x01(\t\x12\x12\n\nreturncode\x18\x03 \x01(\x05\"\x1f\n\x0f\x46ileReadRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"#\n\x10\x46ileReadResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"1\n\x10\x46ileWriteRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"*\n\x11\x46ileWriteResponse\x12\x15\n\rbytes_written\x18\x01 \x01(\x03\"\xc3\x01\n\x0bGateRequest\x12*\n\x04kind\x18\x01 \x01(\x0e\x32\x1c.tangent.execapi.v1.GateKind\x12\x10\n\x08phase_id\x18\x02 \x01(\t\x12\x12\n\nphase_name\x18\x03 \x01(\t\x12\x11\n\ttool_name\x18\x04 \x01(\t\x12\x18\n\x10side_effect_tier\x18\x05 \x01(\t\x12\x14\n\x0c\x61rgs_summary\x18\x06 \x01(\t\x12\x0e\n\x06prompt\x18\x07 \x01(\t\x12\x0f\n\x07options\x18\x08 \x03(\t\"@\n\x0cGateResponse\x12\x12\n\x08\x61pproved\x18\x01 \x01(\x08H\x00\x12\x12\n\x08\x64\x65\x63ision\x18\x02 \x01(\tH\x00\x42\x08\n\x06result*k\n\x08GateKind\x12\x19\n\x15GATE_KIND_UNSPECIFIED\x10\x00\x12\x13\n\x0fGATE_KIND_PHASE\x10\x01\x12\x17\n\x13GATE_KIND_TOOL_CALL\x10\x02\x12\x16\n\x12GATE_KIND_QUESTION\x10\x03\x32P\n\x04\x45xec\x12H\n\x03Run\x12\x1f.tangent.execapi.v1.ExecRequest\x1a .tangent.execapi.v1.ExecResponse2\xb5\x01\n\nFilesystem\x12Q\n\x04Read\x12#.tangent.execapi.v1.FileReadRequest\x1a$.tangent.execapi.v1.FileReadResponse\x12T\n\x05Write\x12$.tangent.execapi.v1.FileWriteRequest\x1a%.tangent.execapi.v1.FileWriteResponse2T\n\x04Gate\x12L\n\x07Request\x12\x1f.tangent.execapi.v1.GateRequest\x1a .tangent.execapi.v1.GateResponseB\x1fZ\x1dshell/internal/execapigrpc/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'execapi.v1.execapi_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\035shell/internal/execapigrpc/pb'
  _globals['_GATEKIND']._serialized_start=598
  _globals['_GATEKIND']._serialized_end=705
  _globals['_EXECREQUEST']._serialized_start=48
  _globals['_EXECREQUEST']._serialized_end=99
  _globals['_EXECRESPONSE']._serialized_start=101
  _globals['_EXECRESPONSE']._serialized_end=167
  _globals['_FILEREADREQUEST']._serialized_start=169
  _globals['_FILEREADREQUEST']._serialized_end=200
  _globals['_FILEREADRESPONSE']._serialized_start=202
  _globals['_FILEREADRESPONSE']._serialized_end=237
  _globals['_FILEWRITEREQUEST']._serialized_start=239
  _globals['_FILEWRITEREQUEST']._serialized_end=288
  _globals['_FILEWRITERESPONSE']._serialized_start=290
  _globals['_FILEWRITERESPONSE']._serialized_end=332
  _globals['_GATEREQUEST']._serialized_start=335
  _globals['_GATEREQUEST']._serialized_end=530
  _globals['_GATERESPONSE']._serialized_start=532
  _globals['_GATERESPONSE']._serialized_end=596
  _globals['_EXEC']._serialized_start=707
  _globals['_EXEC']._serialized_end=787
  _globals['_FILESYSTEM']._serialized_start=790
  _globals['_FILESYSTEM']._serialized_end=971
  _globals['_GATE']._serialized_start=973
  _globals['_GATE']._serialized_end=1057
# @@protoc_insertion_point(module_scope)
