# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from core.execapi_grpc.execapi.v1 import execapi_pb2 as execapi_dot_v1_dot_execapi__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in execapi/v1/execapi_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExecStub:
    """── Exec ─────────────────────────────────────────────────────────────────
    Mirrors tools/shell_exec/handler.py's inputs/outputs exactly (command,
    working_dir in; stdout, stderr, returncode out) so the Python side can
    pass its `inputs` through with minimal translation, same as the HTTP
    execRequest/execResponse shapes did.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Run = channel.unary_unary(
                '/tangent.execapi.v1.Exec/Run',
                request_serializer=execapi_dot_v1_dot_execapi__pb2.ExecRequest.SerializeToString,
                response_deserializer=execapi_dot_v1_dot_execapi__pb2.ExecResponse.FromString,
                _registered_method=True)


class ExecServicer:
    """── Exec ─────────────────────────────────────────────────────────────────
    Mirrors tools/shell_exec/handler.py's inputs/outputs exactly (command,
    working_dir in; stdout, stderr, returncode out) so the Python side can
    pass its `inputs` through with minimal translation, same as the HTTP
    execRequest/execResponse shapes did.
    """

    def Run(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Run': grpc.unary_unary_rpc_method_handler(
                    servicer.Run,
                    request_deserializer=execapi_dot_v1_dot_execapi__pb2.ExecRequest.FromString,
                    response_serializer=execapi_dot_v1_dot_execapi__pb2.ExecResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tangent.execapi.v1.Exec', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tangent.execapi.v1.Exec', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Exec:
    """── Exec ─────────────────────────────────────────────────────────────────
    Mirrors tools/shell_exec/handler.py's inputs/outputs exactly (command,
    working_dir in; stdout, stderr, returncode out) so the Python side can
    pass its `inputs` through with minimal translation, same as the HTTP
    execRequest/execResponse shapes did.
    """

    @staticmethod
    def Run(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tangent.execapi.v1.Exec/Run',
            execapi_dot_v1_dot_execapi__pb2.ExecRequest.SerializeToString,
            execapi_dot_v1_dot_execapi__pb2.ExecResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class FilesystemStub:
    """── Filesystem ───────────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Read = channel.unary_unary(
                '/tangent.execapi.v1.Filesystem/Read',
                request_serializer=execapi_dot_v1_dot_execapi__pb2.FileReadRequest.SerializeToString,
                response_deserializer=execapi_dot_v1_dot_execapi__pb2.FileReadResponse.FromString,
                _registered_method=True)
        self.Write = channel.unary_unary(
                '/tangent.execapi.v1.Filesystem/Write',
                request_serializer=execapi_dot_v1_dot_execapi__pb2.FileWriteRequest.SerializeToString,
                response_deserializer=execapi_dot_v1_dot_execapi__pb2.FileWriteResponse.FromString,
                _registered_method=True)


class FilesystemServicer:
    """── Filesystem ───────────────────────────────────────────────────────────
    """

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Write(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FilesystemServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=execapi_dot_v1_dot_execapi__pb2.FileReadRequest.FromString,
                    response_serializer=execapi_dot_v1_dot_execapi__pb2.FileReadResponse.SerializeToString,
            ),
            'Write': grpc.unary_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=execapi_dot_v1_dot_execapi__pb2.FileWriteRequest.FromString,
                    response_serializer=execapi_dot_v1_dot_execapi__pb2.FileWriteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tangent.execapi.v1.Filesystem', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tangent.execapi.v1.Filesystem', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Filesystem:
    """── Filesystem ───────────────────────────────────────────────────────────
    """

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tangent.execapi.v1.Filesystem/Read',
            execapi_dot_v1_dot_execapi__pb2.FileReadRequest.SerializeToString,
            execapi_dot_v1_dot_execapi__pb2.FileReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tangent.execapi.v1.Filesystem/Write',
            execapi_dot_v1_dot_execapi__pb2.FileWriteRequest.SerializeToString,
            execapi_dot_v1_dot_execapi__pb2.FileWriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GateStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Request = channel.unary_unary(
                '/tangent.execapi.v1.Gate/Request',
                request_serializer=execapi_dot_v1_dot_execapi__pb2.GateRequest.SerializeToString,
                response_deserializer=execapi_dot_v1_dot_execapi__pb2.GateResponse.FromString,
                _registered_method=True)


class GateServicer:
    """Missing associated documentation comment in .proto file."""

    def Request(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GateServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Request': grpc.unary_unary_rpc_method_handler(
                    servicer.Request,
                    request_deserializer=execapi_dot_v1_dot_execapi__pb2.GateRequest.FromString,
                    response_serializer=execapi_dot_v1_dot_execapi__pb2.GateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tangent.execapi.v1.Gate', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tangent.execapi.v1.Gate', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Gate:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Request(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tangent.execapi.v1.Gate/Request',
            execapi_dot_v1_dot_execapi__pb2.GateRequest.SerializeToString,
            execapi_dot_v1_dot_execapi__pb2.GateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
