// The Python-swarm-engine-calls-into-Go-daemon channel: shell_exec routing,
// filesystem read/write, and the unified human-gate primitive (phase /
// tool_call / question). Replaces the old POST /sessions/{id}/exec,
// GET|PUT /sessions/{id}/fs, POST /sessions/{id}/gate HTTP endpoints in
// ide/shell/internal/execapi.
//
// session_id and the bearer token are NOT message fields — both travel as
// gRPC metadata ("authorization: Bearer <token>", "x-session-id: <id>"),
// the same way session_id lived in the URL path (routing, not payload) and
// the token lived in the Authorization header in the HTTP design this
// replaces.
//
// GateRequest deliberately has no timeout_seconds field: the caller sets
// the RPC's own deadline (grpc's native per-call timeout) instead of
// passing a separate value the server has to trust — the Go Gate service
// reads it back via ctx.Deadline().

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.31.1
// source: ide/shell/proto/execapi/v1/execapi.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Exec_Run_FullMethodName = "/tangent.execapi.v1.Exec/Run"
)

// ExecClient is the client API for Exec service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ── Exec ─────────────────────────────────────────────────────────────────
// Mirrors tools/shell_exec/handler.py's inputs/outputs exactly (command,
// working_dir in; stdout, stderr, returncode out) so the Python side can
// pass its `inputs` through with minimal translation, same as the HTTP
// execRequest/execResponse shapes did.
type ExecClient interface {
	Run(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error)
}

type execClient struct {
	cc grpc.ClientConnInterface
}

func NewExecClient(cc grpc.ClientConnInterface) ExecClient {
	return &execClient{cc}
}

func (c *execClient) Run(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecResponse)
	err := c.cc.Invoke(ctx, Exec_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExecServer is the server API for Exec service.
// All implementations must embed UnimplementedExecServer
// for forward compatibility.
//
// ── Exec ─────────────────────────────────────────────────────────────────
// Mirrors tools/shell_exec/handler.py's inputs/outputs exactly (command,
// working_dir in; stdout, stderr, returncode out) so the Python side can
// pass its `inputs` through with minimal translation, same as the HTTP
// execRequest/execResponse shapes did.
type ExecServer interface {
	Run(context.Context, *ExecRequest) (*ExecResponse, error)
	mustEmbedUnimplementedExecServer()
}

// UnimplementedExecServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExecServer struct{}

func (UnimplementedExecServer) Run(context.Context, *ExecRequest) (*ExecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedExecServer) mustEmbedUnimplementedExecServer() {}
func (UnimplementedExecServer) testEmbeddedByValue()              {}

// UnsafeExecServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExecServer will
// result in compilation errors.
type UnsafeExecServer interface {
	mustEmbedUnimplementedExecServer()
}

func RegisterExecServer(s grpc.ServiceRegistrar, srv ExecServer) {
	// If the following call panics, it indicates UnimplementedExecServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Exec_ServiceDesc, srv)
}

func _Exec_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exec_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecServer).Run(ctx, req.(*ExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Exec_ServiceDesc is the grpc.ServiceDesc for Exec service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Exec_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tangent.execapi.v1.Exec",
	HandlerType: (*ExecServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _Exec_Run_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ide/shell/proto/execapi/v1/execapi.proto",
}

const (
	Filesystem_Read_FullMethodName  = "/tangent.execapi.v1.Filesystem/Read"
	Filesystem_Write_FullMethodName = "/tangent.execapi.v1.Filesystem/Write"
)

// FilesystemClient is the client API for Filesystem service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ── Filesystem ───────────────────────────────────────────────────────────
type FilesystemClient interface {
	Read(ctx context.Context, in *FileReadRequest, opts ...grpc.CallOption) (*FileReadResponse, error)
	Write(ctx context.Context, in *FileWriteRequest, opts ...grpc.CallOption) (*FileWriteResponse, error)
}

type filesystemClient struct {
	cc grpc.ClientConnInterface
}

func NewFilesystemClient(cc grpc.ClientConnInterface) FilesystemClient {
	return &filesystemClient{cc}
}

func (c *filesystemClient) Read(ctx context.Context, in *FileReadRequest, opts ...grpc.CallOption) (*FileReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileReadResponse)
	err := c.cc.Invoke(ctx, Filesystem_Read_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filesystemClient) Write(ctx context.Context, in *FileWriteRequest, opts ...grpc.CallOption) (*FileWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileWriteResponse)
	err := c.cc.Invoke(ctx, Filesystem_Write_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FilesystemServer is the server API for Filesystem service.
// All implementations must embed UnimplementedFilesystemServer
// for forward compatibility.
//
// ── Filesystem ───────────────────────────────────────────────────────────
type FilesystemServer interface {
	Read(context.Context, *FileReadRequest) (*FileReadResponse, error)
	Write(context.Context, *FileWriteRequest) (*FileWriteResponse, error)
	mustEmbedUnimplementedFilesystemServer()
}

// UnimplementedFilesystemServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFilesystemServer struct{}

func (UnimplementedFilesystemServer) Read(context.Context, *FileReadRequest) (*FileReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedFilesystemServer) Write(context.Context, *FileWriteRequest) (*FileWriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedFilesystemServer) mustEmbedUnimplementedFilesystemServer() {}
func (UnimplementedFilesystemServer) testEmbeddedByValue()                    {}

// UnsafeFilesystemServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FilesystemServer will
// result in compilation errors.
type UnsafeFilesystemServer interface {
	mustEmbedUnimplementedFilesystemServer()
}

func RegisterFilesystemServer(s grpc.ServiceRegistrar, srv FilesystemServer) {
	// If the following call panics, it indicates UnimplementedFilesystemServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Filesystem_ServiceDesc, srv)
}

func _Filesystem_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesystemServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Filesystem_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesystemServer).Read(ctx, req.(*FileReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Filesystem_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesystemServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Filesystem_Write_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesystemServer).Write(ctx, req.(*FileWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Filesystem_ServiceDesc is the grpc.ServiceDesc for Filesystem service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Filesystem_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tangent.execapi.v1.Filesystem",
	HandlerType: (*FilesystemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Read",
			Handler:    _Filesystem_Read_Handler,
		},
		{
			MethodName: "Write",
			Handler:    _Filesystem_Write_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ide/shell/proto/execapi/v1/execapi.proto",
}

const (
	Gate_Request_FullMethodName = "/tangent.execapi.v1.Gate/Request"
)

// GateClient is the client API for Gate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GateClient interface {
	Request(ctx context.Context, in *GateRequest, opts ...grpc.CallOption) (*GateResponse, error)
}

type gateClient struct {
	cc grpc.ClientConnInterface
}

func NewGateClient(cc grpc.ClientConnInterface) GateClient {
	return &gateClient{cc}
}

func (c *gateClient) Request(ctx context.Context, in *GateRequest, opts ...grpc.CallOption) (*GateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GateResponse)
	err := c.cc.Invoke(ctx, Gate_Request_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GateServer is the server API for Gate service.
// All implementations must embed UnimplementedGateServer
// for forward compatibility.
type GateServer interface {
	Request(context.Context, *GateRequest) (*GateResponse, error)
	mustEmbedUnimplementedGateServer()
}

// UnimplementedGateServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGateServer struct{}

func (UnimplementedGateServer) Request(context.Context, *GateRequest) (*GateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Request not implemented")
}
func (UnimplementedGateServer) mustEmbedUnimplementedGateServer() {}
func (UnimplementedGateServer) testEmbeddedByValue()              {}

// UnsafeGateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GateServer will
// result in compilation errors.
type UnsafeGateServer interface {
	mustEmbedUnimplementedGateServer()
}

func RegisterGateServer(s grpc.ServiceRegistrar, srv GateServer) {
	// If the following call panics, it indicates UnimplementedGateServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Gate_ServiceDesc, srv)
}

func _Gate_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gate_Request_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).Request(ctx, req.(*GateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Gate_ServiceDesc is the grpc.ServiceDesc for Gate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tangent.execapi.v1.Gate",
	HandlerType: (*GateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Request",
			Handler:    _Gate_Request_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ide/shell/proto/execapi/v1/execapi.proto",
}
