// The Python-swarm-engine-calls-into-Go-daemon channel: shell_exec routing,
// filesystem read/write, and the unified human-gate primitive (phase /
// tool_call / question). Replaces the old POST /sessions/{id}/exec,
// GET|PUT /sessions/{id}/fs, POST /sessions/{id}/gate HTTP endpoints in
// ide/shell/internal/execapi.
//
// session_id and the bearer token are NOT message fields — both travel as
// gRPC metadata ("authorization: Bearer <token>", "x-session-id: <id>"),
// the same way session_id lived in the URL path (routing, not payload) and
// the token lived in the Authorization header in the HTTP design this
// replaces.
//
// GateRequest deliberately has no timeout_seconds field: the caller sets
// the RPC's own deadline (grpc's native per-call timeout) instead of
// passing a separate value the server has to trust — the Go Gate service
// reads it back via ctx.Deadline().

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.31.1
// source: ide/shell/proto/execapi/v1/execapi.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ── Gate ─────────────────────────────────────────────────────────────────
// One generic primitive, matching the existing HTTP design (POST
// /sessions/{id}/gate with a "kind" field) rather than three separate
// RPCs — see coordination/orchestrator.py's _daemon_gate_request /
// _daemon_ws_requester and coordination/safety.py's
// _daemon_confirm_tool_call, all three of which already share one HTTP
// endpoint today.
type GateKind int32

const (
	GateKind_GATE_KIND_UNSPECIFIED GateKind = 0
	GateKind_GATE_KIND_PHASE       GateKind = 1
	GateKind_GATE_KIND_TOOL_CALL   GateKind = 2
	GateKind_GATE_KIND_QUESTION    GateKind = 3
)

// Enum value maps for GateKind.
var (
	GateKind_name = map[int32]string{
		0: "GATE_KIND_UNSPECIFIED",
		1: "GATE_KIND_PHASE",
		2: "GATE_KIND_TOOL_CALL",
		3: "GATE_KIND_QUESTION",
	}
	GateKind_value = map[string]int32{
		"GATE_KIND_UNSPECIFIED": 0,
		"GATE_KIND_PHASE":       1,
		"GATE_KIND_TOOL_CALL":   2,
		"GATE_KIND_QUESTION":    3,
	}
)

func (x GateKind) Enum() *GateKind {
	p := new(GateKind)
	*p = x
	return p
}

func (x GateKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GateKind) Descriptor() protoreflect.EnumDescriptor {
	return file_ide_shell_proto_execapi_v1_execapi_proto_enumTypes[0].Descriptor()
}

func (GateKind) Type() protoreflect.EnumType {
	return &file_ide_shell_proto_execapi_v1_execapi_proto_enumTypes[0]
}

func (x GateKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GateKind.Descriptor instead.
func (GateKind) EnumDescriptor() ([]byte, []int) {
	return file_ide_shell_proto_execapi_v1_execapi_proto_rawDescGZIP(), []int{0}
}

type ExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	WorkingDir    string                 `protobuf:"bytes,2,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_ide_shell_proto_execapi_v1_execapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ide_shell_proto_execapi_v1_execapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_ide_shell_proto_execapi_v1_execapi_proto_rawDescGZIP(), []int{0}
}

func (x *ExecRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

type ExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        string                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	Returncode    int32                  `protobuf:"varint,3,opt,name=returncode,proto3" json:"returncode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_ide_shell_proto_execapi_v1_execapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ide_shell_proto_execapi_v1_execapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_ide_shell_proto_execapi_v1_execapi_proto_rawDescGZIP(), []int{1}
}

func (x *ExecResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecResponse) GetReturncode() int32 {
	if x != nil {
		return x.Returncode
	}
	return 0
}

type FileReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileReadRequest) Reset() {
	*x = FileReadRequest{}
	mi := &file_ide_shell_proto_execapi_v1_execapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileReadRequest) ProtoMessage() {}

func (x *FileReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ide_shell_proto_execapi_v1_execapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileReadRequest.ProtoReflect.Descriptor instead.
func (*FileReadRequest) Descriptor() ([]byte, []int) {
	return file_ide_shell_proto_execapi_v1_execapi_proto_rawDescGZIP(), []int{2}
}

func (x *FileReadRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FileReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileReadResponse) Reset() {
	*x = FileReadResponse{}
	mi := &file_ide_shell_proto_execapi_v1_execapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileReadResponse) ProtoMessage() {}

func (x *FileReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ide_shell_proto_execapi_v1_execapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileReadResponse.ProtoReflect.Descriptor instead.
func (*FileReadResponse) Descriptor() ([]byte, []int) {
	return file_ide_shell_proto_execapi_v1_execapi_proto_rawDescGZIP(), []int{3}
}

func (x *FileReadResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type FileWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileWriteRequest) Reset() {
	*x = FileWriteRequest{}
	mi := &file_ide_shell_proto_execapi_v1_execapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileWriteRequest) ProtoMessage() {}

func (x *FileWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ide_shell_proto_execapi_v1_execapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileWriteRequest.ProtoReflect.Descriptor instead.
func (*FileWriteRequest) Descriptor() ([]byte, []int) {
	return file_ide_shell_proto_execapi_v1_execapi_proto_rawDescGZIP(), []int{4}
}

func (x *FileWriteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileWriteRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type FileWriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesWritten  int64                  `protobuf:"varint,1,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileWriteResponse) Reset() {
	*x = FileWriteResponse{}
	mi := &file_ide_shell_proto_execapi_v1_execapi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileWriteResponse) ProtoMessage() {}

func (x *FileWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ide_shell_proto_execapi_v1_execapi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileWriteResponse.ProtoReflect.Descriptor instead.
func (*FileWriteResponse) Descriptor() ([]byte, []int) {
	return file_ide_shell_proto_execapi_v1_execapi_proto_rawDescGZIP(), []int{5}
}

func (x *FileWriteResponse) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

type GateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  GateKind               `protobuf:"varint,1,opt,name=kind,proto3,enum=tangent.execapi.v1.GateKind" json:"kind,omitempty"`
	// GATE_KIND_PHASE
	PhaseId   string `protobuf:"bytes,2,opt,name=phase_id,json=phaseId,proto3" json:"phase_id,omitempty"`
	PhaseName string `protobuf:"bytes,3,opt,name=phase_name,json=phaseName,proto3" json:"phase_name,omitempty"`
	// GATE_KIND_TOOL_CALL
	ToolName       string `protobuf:"bytes,4,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	SideEffectTier string `protobuf:"bytes,5,opt,name=side_effect_tier,json=sideEffectTier,proto3" json:"side_effect_tier,omitempty"`
	ArgsSummary    string `protobuf:"bytes,6,opt,name=args_summary,json=argsSummary,proto3" json:"args_summary,omitempty"`
	// GATE_KIND_QUESTION
	Prompt        string   `protobuf:"bytes,7,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Options       []string `protobuf:"bytes,8,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GateRequest) Reset() {
	*x = GateRequest{}
	mi := &file_ide_shell_proto_execapi_v1_execapi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateRequest) ProtoMessage() {}

func (x *GateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ide_shell_proto_execapi_v1_execapi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateRequest.ProtoReflect.Descriptor instead.
func (*GateRequest) Descriptor() ([]byte, []int) {
	return file_ide_shell_proto_execapi_v1_execapi_proto_rawDescGZIP(), []int{6}
}

func (x *GateRequest) GetKind() GateKind {
	if x != nil {
		return x.Kind
	}
	return GateKind_GATE_KIND_UNSPECIFIED
}

func (x *GateRequest) GetPhaseId() string {
	if x != nil {
		return x.PhaseId
	}
	return ""
}

func (x *GateRequest) GetPhaseName() string {
	if x != nil {
		return x.PhaseName
	}
	return ""
}

func (x *GateRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *GateRequest) GetSideEffectTier() string {
	if x != nil {
		return x.SideEffectTier
	}
	return ""
}

func (x *GateRequest) GetArgsSummary() string {
	if x != nil {
		return x.ArgsSummary
	}
	return ""
}

func (x *GateRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GateRequest) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

// The two real distinct response shapes (approved: bool for phase/
// tool_call, decision: string — free text or a selected option — for
// question) as a oneof, rather than overloading one field ambiguously
// (e.g. stuffing "true"/"false" into the same string field a real answer
// like "us-east-1" would occupy).
type GateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*GateResponse_Approved
	//	*GateResponse_Decision
	Result        isGateResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GateResponse) Reset() {
	*x = GateResponse{}
	mi := &file_ide_shell_proto_execapi_v1_execapi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateResponse) ProtoMessage() {}

func (x *GateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ide_shell_proto_execapi_v1_execapi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateResponse.ProtoReflect.Descriptor instead.
func (*GateResponse) Descriptor() ([]byte, []int) {
	return file_ide_shell_proto_execapi_v1_execapi_proto_rawDescGZIP(), []int{7}
}

func (x *GateResponse) GetResult() isGateResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GateResponse) GetApproved() bool {
	if x != nil {
		if x, ok := x.Result.(*GateResponse_Approved); ok {
			return x.Approved
		}
	}
	return false
}

func (x *GateResponse) GetDecision() string {
	if x != nil {
		if x, ok := x.Result.(*GateResponse_Decision); ok {
			return x.Decision
		}
	}
	return ""
}

type isGateResponse_Result interface {
	isGateResponse_Result()
}

type GateResponse_Approved struct {
	Approved bool `protobuf:"varint,1,opt,name=approved,proto3,oneof"`
}

type GateResponse_Decision struct {
	Decision string `protobuf:"bytes,2,opt,name=decision,proto3,oneof"`
}

func (*GateResponse_Approved) isGateResponse_Result() {}

func (*GateResponse_Decision) isGateResponse_Result() {}

var File_ide_shell_proto_execapi_v1_execapi_proto protoreflect.FileDescriptor

const file_ide_shell_proto_execapi_v1_execapi_proto_rawDesc = "" +
	"\n" +
	"(ide/shell/proto/execapi/v1/execapi.proto\x12\x12tangent.execapi.v1\"H\n" +
	"\vExecRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x1f\n" +
	"\vworking_dir\x18\x02 \x01(\tR\n" +
	"workingDir\"^\n" +
	"\fExecResponse\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\tR\x06stderr\x12\x1e\n" +
	"\n" +
	"returncode\x18\x03 \x01(\x05R\n" +
	"returncode\"%\n" +
	"\x0fFileReadRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\",\n" +
	"\x10FileReadResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\"@\n" +
	"\x10FileWriteRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"8\n" +
	"\x11FileWriteResponse\x12#\n" +
	"\rbytes_written\x18\x01 \x01(\x03R\fbytesWritten\"\x95\x02\n" +
	"\vGateRequest\x120\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1c.tangent.execapi.v1.GateKindR\x04kind\x12\x19\n" +
	"\bphase_id\x18\x02 \x01(\tR\aphaseId\x12\x1d\n" +
	"\n" +
	"phase_name\x18\x03 \x01(\tR\tphaseName\x12\x1b\n" +
	"\ttool_name\x18\x04 \x01(\tR\btoolName\x12(\n" +
	"\x10side_effect_tier\x18\x05 \x01(\tR\x0esideEffectTier\x12!\n" +
	"\fargs_summary\x18\x06 \x01(\tR\vargsSummary\x12\x16\n" +
	"\x06prompt\x18\a \x01(\tR\x06prompt\x12\x18\n" +
	"\aoptions\x18\b \x03(\tR\aoptions\"T\n" +
	"\fGateResponse\x12\x1c\n" +
	"\bapproved\x18\x01 \x01(\bH\x00R\bapproved\x12\x1c\n" +
	"\bdecision\x18\x02 \x01(\tH\x00R\bdecisionB\b\n" +
	"\x06result*k\n" +
	"\bGateKind\x12\x19\n" +
	"\x15GATE_KIND_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fGATE_KIND_PHASE\x10\x01\x12\x17\n" +
	"\x13GATE_KIND_TOOL_CALL\x10\x02\x12\x16\n" +
	"\x12GATE_KIND_QUESTION\x10\x032P\n" +
	"\x04Exec\x12H\n" +
	"\x03Run\x12\x1f.tangent.execapi.v1.ExecRequest\x1a .tangent.execapi.v1.ExecResponse2\xb5\x01\n" +
	"\n" +
	"Filesystem\x12Q\n" +
	"\x04Read\x12#.tangent.execapi.v1.FileReadRequest\x1a$.tangent.execapi.v1.FileReadResponse\x12T\n" +
	"\x05Write\x12$.tangent.execapi.v1.FileWriteRequest\x1a%.tangent.execapi.v1.FileWriteResponse2T\n" +
	"\x04Gate\x12L\n" +
	"\aRequest\x12\x1f.tangent.execapi.v1.GateRequest\x1a .tangent.execapi.v1.GateResponseB\x1fZ\x1dshell/internal/execapigrpc/pbb\x06proto3"

var (
	file_ide_shell_proto_execapi_v1_execapi_proto_rawDescOnce sync.Once
	file_ide_shell_proto_execapi_v1_execapi_proto_rawDescData []byte
)

func file_ide_shell_proto_execapi_v1_execapi_proto_rawDescGZIP() []byte {
	file_ide_shell_proto_execapi_v1_execapi_proto_rawDescOnce.Do(func() {
		file_ide_shell_proto_execapi_v1_execapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ide_shell_proto_execapi_v1_execapi_proto_rawDesc), len(file_ide_shell_proto_execapi_v1_execapi_proto_rawDesc)))
	})
	return file_ide_shell_proto_execapi_v1_execapi_proto_rawDescData
}

var file_ide_shell_proto_execapi_v1_execapi_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ide_shell_proto_execapi_v1_execapi_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_ide_shell_proto_execapi_v1_execapi_proto_goTypes = []any{
	(GateKind)(0),             // 0: tangent.execapi.v1.GateKind
	(*ExecRequest)(nil),       // 1: tangent.execapi.v1.ExecRequest
	(*ExecResponse)(nil),      // 2: tangent.execapi.v1.ExecResponse
	(*FileReadRequest)(nil),   // 3: tangent.execapi.v1.FileReadRequest
	(*FileReadResponse)(nil),  // 4: tangent.execapi.v1.FileReadResponse
	(*FileWriteRequest)(nil),  // 5: tangent.execapi.v1.FileWriteRequest
	(*FileWriteResponse)(nil), // 6: tangent.execapi.v1.FileWriteResponse
	(*GateRequest)(nil),       // 7: tangent.execapi.v1.GateRequest
	(*GateResponse)(nil),      // 8: tangent.execapi.v1.GateResponse
}
var file_ide_shell_proto_execapi_v1_execapi_proto_depIdxs = []int32{
	0, // 0: tangent.execapi.v1.GateRequest.kind:type_name -> tangent.execapi.v1.GateKind
	1, // 1: tangent.execapi.v1.Exec.Run:input_type -> tangent.execapi.v1.ExecRequest
	3, // 2: tangent.execapi.v1.Filesystem.Read:input_type -> tangent.execapi.v1.FileReadRequest
	5, // 3: tangent.execapi.v1.Filesystem.Write:input_type -> tangent.execapi.v1.FileWriteRequest
	7, // 4: tangent.execapi.v1.Gate.Request:input_type -> tangent.execapi.v1.GateRequest
	2, // 5: tangent.execapi.v1.Exec.Run:output_type -> tangent.execapi.v1.ExecResponse
	4, // 6: tangent.execapi.v1.Filesystem.Read:output_type -> tangent.execapi.v1.FileReadResponse
	6, // 7: tangent.execapi.v1.Filesystem.Write:output_type -> tangent.execapi.v1.FileWriteResponse
	8, // 8: tangent.execapi.v1.Gate.Request:output_type -> tangent.execapi.v1.GateResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ide_shell_proto_execapi_v1_execapi_proto_init() }
func file_ide_shell_proto_execapi_v1_execapi_proto_init() {
	if File_ide_shell_proto_execapi_v1_execapi_proto != nil {
		return
	}
	file_ide_shell_proto_execapi_v1_execapi_proto_msgTypes[7].OneofWrappers = []any{
		(*GateResponse_Approved)(nil),
		(*GateResponse_Decision)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ide_shell_proto_execapi_v1_execapi_proto_rawDesc), len(file_ide_shell_proto_execapi_v1_execapi_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_ide_shell_proto_execapi_v1_execapi_proto_goTypes,
		DependencyIndexes: file_ide_shell_proto_execapi_v1_execapi_proto_depIdxs,
		EnumInfos:         file_ide_shell_proto_execapi_v1_execapi_proto_enumTypes,
		MessageInfos:      file_ide_shell_proto_execapi_v1_execapi_proto_msgTypes,
	}.Build()
	File_ide_shell_proto_execapi_v1_execapi_proto = out.File
	file_ide_shell_proto_execapi_v1_execapi_proto_goTypes = nil
	file_ide_shell_proto_execapi_v1_execapi_proto_depIdxs = nil
}
