// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseTerminal(arg1) {
  return window['go']['main']['SessionAPI']['CloseTerminal'](arg1);
}

export function CreateTerminal(arg1, arg2, arg3) {
  return window['go']['main']['SessionAPI']['CreateTerminal'](arg1, arg2, arg3);
}

export function CreateWorkspaceFolder(arg1, arg2) {
  return window['go']['main']['SessionAPI']['CreateWorkspaceFolder'](arg1, arg2);
}

export function DeleteWorkspacePath(arg1, arg2) {
  return window['go']['main']['SessionAPI']['DeleteWorkspacePath'](arg1, arg2);
}

export function GetContracts(arg1) {
  return window['go']['main']['SessionAPI']['GetContracts'](arg1);
}

export function GetCost(arg1) {
  return window['go']['main']['SessionAPI']['GetCost'](arg1);
}

export function GetProviderKeyStatus() {
  return window['go']['main']['SessionAPI']['GetProviderKeyStatus']();
}

export function GetTrace(arg1) {
  return window['go']['main']['SessionAPI']['GetTrace'](arg1);
}

export function GetUserHomePath() {
  return window['go']['main']['SessionAPI']['GetUserHomePath']();
}

export function GetWorkspaceDir(arg1, arg2) {
  return window['go']['main']['SessionAPI']['GetWorkspaceDir'](arg1, arg2);
}

export function GetWorkspaceTree(arg1) {
  return window['go']['main']['SessionAPI']['GetWorkspaceTree'](arg1);
}

export function GetWorkspaceTreeAt(arg1) {
  return window['go']['main']['SessionAPI']['GetWorkspaceTreeAt'](arg1);
}

export function GitBranches(arg1) {
  return window['go']['main']['SessionAPI']['GitBranches'](arg1);
}

export function GitCheckout(arg1, arg2) {
  return window['go']['main']['SessionAPI']['GitCheckout'](arg1, arg2);
}

export function GitCommit(arg1, arg2, arg3) {
  return window['go']['main']['SessionAPI']['GitCommit'](arg1, arg2, arg3);
}

export function GitCreateBranch(arg1, arg2) {
  return window['go']['main']['SessionAPI']['GitCreateBranch'](arg1, arg2);
}

export function GitDiff(arg1, arg2, arg3) {
  return window['go']['main']['SessionAPI']['GitDiff'](arg1, arg2, arg3);
}

export function GitDiscard(arg1, arg2) {
  return window['go']['main']['SessionAPI']['GitDiscard'](arg1, arg2);
}

export function GitFetch(arg1) {
  return window['go']['main']['SessionAPI']['GitFetch'](arg1);
}

export function GitHubCreatePR(arg1, arg2, arg3, arg4) {
  return window['go']['main']['SessionAPI']['GitHubCreatePR'](arg1, arg2, arg3, arg4);
}

export function GitHubCurrentPR(arg1) {
  return window['go']['main']['SessionAPI']['GitHubCurrentPR'](arg1);
}

export function GitHubDefaultBranch(arg1) {
  return window['go']['main']['SessionAPI']['GitHubDefaultBranch'](arg1);
}

export function GitHubListPRs(arg1) {
  return window['go']['main']['SessionAPI']['GitHubListPRs'](arg1);
}

export function GitHubStatus(arg1) {
  return window['go']['main']['SessionAPI']['GitHubStatus'](arg1);
}

export function GitLog(arg1, arg2) {
  return window['go']['main']['SessionAPI']['GitLog'](arg1, arg2);
}

export function GitPull(arg1) {
  return window['go']['main']['SessionAPI']['GitPull'](arg1);
}

export function GitPush(arg1) {
  return window['go']['main']['SessionAPI']['GitPush'](arg1);
}

export function GitStage(arg1, arg2) {
  return window['go']['main']['SessionAPI']['GitStage'](arg1, arg2);
}

export function GitStatus(arg1) {
  return window['go']['main']['SessionAPI']['GitStatus'](arg1);
}

export function GitSync(arg1) {
  return window['go']['main']['SessionAPI']['GitSync'](arg1);
}

export function GitUnstage(arg1, arg2) {
  return window['go']['main']['SessionAPI']['GitUnstage'](arg1, arg2);
}

export function ListSessions() {
  return window['go']['main']['SessionAPI']['ListSessions']();
}

export function LogFrontendError(arg1) {
  return window['go']['main']['SessionAPI']['LogFrontendError'](arg1);
}

export function ReadFile(arg1, arg2) {
  return window['go']['main']['SessionAPI']['ReadFile'](arg1, arg2);
}

export function ReadWorkspaceFile(arg1, arg2) {
  return window['go']['main']['SessionAPI']['ReadWorkspaceFile'](arg1, arg2);
}

export function RenameWorkspacePath(arg1, arg2, arg3) {
  return window['go']['main']['SessionAPI']['RenameWorkspacePath'](arg1, arg2, arg3);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['SessionAPI']['ResizeTerminal'](arg1, arg2, arg3);
}

export function ResolveGate(arg1, arg2, arg3) {
  return window['go']['main']['SessionAPI']['ResolveGate'](arg1, arg2, arg3);
}

export function SearchWorkspace(arg1, arg2) {
  return window['go']['main']['SessionAPI']['SearchWorkspace'](arg1, arg2);
}

export function SelectWorkspace() {
  return window['go']['main']['SessionAPI']['SelectWorkspace']();
}

export function SetProviderKey(arg1, arg2, arg3) {
  return window['go']['main']['SessionAPI']['SetProviderKey'](arg1, arg2, arg3);
}

export function StartSession(arg1, arg2, arg3) {
  return window['go']['main']['SessionAPI']['StartSession'](arg1, arg2, arg3);
}

export function StopSession(arg1) {
  return window['go']['main']['SessionAPI']['StopSession'](arg1);
}

export function ValidateWorkspacePath(arg1) {
  return window['go']['main']['SessionAPI']['ValidateWorkspacePath'](arg1);
}

export function WriteFile(arg1, arg2, arg3) {
  return window['go']['main']['SessionAPI']['WriteFile'](arg1, arg2, arg3);
}

export function WriteTerminal(arg1, arg2) {
  return window['go']['main']['SessionAPI']['WriteTerminal'](arg1, arg2);
}

export function WriteWorkspaceFile(arg1, arg2, arg3) {
  return window['go']['main']['SessionAPI']['WriteWorkspaceFile'](arg1, arg2, arg3);
}
