// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {session} from '../models';

export function GetContracts(arg1:string):Promise<Array<session.ContractEntry>>;

export function GetCost(arg1:string):Promise<session.CostReport>;

export function GetTrace(arg1:string):Promise<Array<session.TraceEntry>>;

export function GetWorkspaceTree(arg1:string):Promise<Array<session.FileNode>>;

export function ListSessions():Promise<Array<session.SessionSummary>>;

export function ReadFile(arg1:string,arg2:string):Promise<session.FileContent>;

export function ResolveGate(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StartSession(arg1:string,arg2:string,arg3:string):Promise<session.StartSessionResult>;

export function StopSession(arg1:string):Promise<void>;

export function WriteFile(arg1:string,arg2:string,arg3:string):Promise<void>;
