// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {session} from '../models';

export function CloseTerminal(arg1:string):Promise<void>;

export function CreateTerminal(arg1:string,arg2:number,arg3:number):Promise<main.LocalTerminalInfo>;

export function CreateWorkspaceFolder(arg1:string,arg2:string):Promise<void>;

export function DeleteWorkspacePath(arg1:string,arg2:string):Promise<void>;

export function GetContracts(arg1:string):Promise<Array<session.ContractEntry>>;

export function GetCost(arg1:string):Promise<session.CostReport>;

export function GetProviderKeyStatus():Promise<main.ProviderKeyStatus>;

export function GetTrace(arg1:string):Promise<Array<session.TraceEntry>>;

export function GetUserHomePath():Promise<string>;

export function GetWorkspaceDir(arg1:string,arg2:string):Promise<Array<session.FileNode>>;

export function GetWorkspaceTree(arg1:string):Promise<Array<session.FileNode>>;

export function GetWorkspaceTreeAt(arg1:string):Promise<Array<session.FileNode>>;

export function GitBranches(arg1:string):Promise<Array<main.GitBranch>>;

export function GitCheckout(arg1:string,arg2:string):Promise<void>;

export function GitCommit(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function GitCreateBranch(arg1:string,arg2:string):Promise<void>;

export function GitDiff(arg1:string,arg2:string,arg3:boolean):Promise<main.GitDiff>;

export function GitDiscard(arg1:string,arg2:Array<string>):Promise<void>;

export function GitFetch(arg1:string):Promise<void>;

export function GitHubCreatePR(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.GitHubPR>;

export function GitHubCurrentPR(arg1:string):Promise<main.GitHubPR>;

export function GitHubDefaultBranch(arg1:string):Promise<string>;

export function GitHubListPRs(arg1:string):Promise<Array<main.GitHubPRListItem>>;

export function GitHubStatus(arg1:string):Promise<main.GitHubStatus>;

export function GitLog(arg1:string,arg2:number):Promise<Array<main.GitHubCommit>>;

export function GitPull(arg1:string):Promise<void>;

export function GitPush(arg1:string):Promise<void>;

export function GitStage(arg1:string,arg2:Array<string>):Promise<void>;

export function GitStatus(arg1:string):Promise<main.GitStatus>;

export function GitSync(arg1:string):Promise<void>;

export function GitUnstage(arg1:string,arg2:Array<string>):Promise<void>;

export function ListSessions():Promise<Array<session.SessionSummary>>;

export function LogFrontendError(arg1:string):Promise<void>;

export function ReadFile(arg1:string,arg2:string):Promise<session.FileContent>;

export function ReadWorkspaceFile(arg1:string,arg2:string):Promise<session.FileContent>;

export function RenameWorkspacePath(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResolveGate(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SearchWorkspace(arg1:string,arg2:string):Promise<Array<main.SearchMatch>>;

export function SelectWorkspace():Promise<main.WorkspaceInfo>;

export function SetProviderKey(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StartSession(arg1:string,arg2:string,arg3:string):Promise<session.StartSessionResult>;

export function StopSession(arg1:string):Promise<void>;

export function ValidateWorkspacePath(arg1:string):Promise<main.WorkspaceInfo>;

export function WriteFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteTerminal(arg1:string,arg2:string):Promise<void>;

export function WriteWorkspaceFile(arg1:string,arg2:string,arg3:string):Promise<void>;
