// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetContracts(arg1) {
  return window['go']['main']['SessionAPI']['GetContracts'](arg1);
}

export function GetCost(arg1) {
  return window['go']['main']['SessionAPI']['GetCost'](arg1);
}

export function GetTrace(arg1) {
  return window['go']['main']['SessionAPI']['GetTrace'](arg1);
}

export function GetWorkspaceTree(arg1) {
  return window['go']['main']['SessionAPI']['GetWorkspaceTree'](arg1);
}

export function ListSessions() {
  return window['go']['main']['SessionAPI']['ListSessions']();
}

export function ReadFile(arg1, arg2) {
  return window['go']['main']['SessionAPI']['ReadFile'](arg1, arg2);
}

export function ResolveGate(arg1, arg2, arg3) {
  return window['go']['main']['SessionAPI']['ResolveGate'](arg1, arg2, arg3);
}

export function StartSession(arg1, arg2) {
  return window['go']['main']['SessionAPI']['StartSession'](arg1, arg2);
}

export function StopSession(arg1) {
  return window['go']['main']['SessionAPI']['StopSession'](arg1);
}

export function WriteFile(arg1, arg2, arg3) {
  return window['go']['main']['SessionAPI']['WriteFile'](arg1, arg2, arg3);
}
